export const LOGIC_ARENA_STACKS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "React",
  "Next.js",
  "Node.js",
  "SQL",
  "MongoDB",
  "HTML",
  "CSS",
  "Git",
  "DevOps",
  "Data Structures",
  "Algorithms",
  "Aptitude",
  "Logical Reasoning",
] as const;

export const LOGIC_ARENA_MODES = [
  {
    id: "concept-sprint",
    label: "Concept Sprint",
    description: "Fast conceptual MCQs from the selected stack.",
  },
  {
    id: "output-challenge",
    label: "Output Challenge",
    description: "Predict the output or the next state of the code.",
  },
  {
    id: "debug-duel",
    label: "Debug Duel",
    description: "Spot the issue and pick the right correction.",
  },
] as const;

export const LOGIC_ARENA_DIFFICULTIES = [
  "Beginner",
  "Intermediate",
  "Advanced",
] as const;

export const LOGIC_ARENA_QUESTION_LIMITS = {
  min: 5,
  max: 20,
} as const;

export const FALLBACK_LOGIC_ARENA_QUESTIONS = [
  {
    id: "js-closure-1",
    stack: "JavaScript",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "Which statement best describes a closure in JavaScript?",
    options: [
      "A loop that never stops executing",
      "A function bundled with access to its lexical scope",
      "A method that closes a browser tab",
      "A syntax rule for ending blocks",
    ],
    answerIndex: 1,
    explanation:
      "A closure lets a function retain access to variables from the scope where it was created.",
    tags: ["functions", "scope"],
  },
  {
    id: "ts-union-1",
    stack: "TypeScript",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "What is the main use of a union type in TypeScript?",
    options: [
      "To combine CSS classes",
      "To allow a value to be one of multiple types",
      "To join two arrays permanently",
      "To inherit methods from two classes",
    ],
    answerIndex: 1,
    explanation:
      "Union types, like string | number, let a variable safely accept more than one type.",
    tags: ["types", "basics"],
  },
  {
    id: "py-list-1",
    stack: "Python",
    difficulty: "Beginner",
    mode: "output-challenge",
    question: "What is the output of len([1, 2, [3, 4]]) in Python?",
    options: ["2", "3", "4", "Error"],
    answerIndex: 1,
    explanation:
      "The outer list contains three elements: 1, 2, and [3, 4].",
    tags: ["lists", "output"],
  },
  {
    id: "java-oop-1",
    stack: "Java",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "Which OOP concept allows a subclass to provide its own implementation of a method?",
    options: ["Encapsulation", "Abstraction", "Overriding", "Overloading"],
    answerIndex: 2,
    explanation:
      "Method overriding happens when a subclass redefines a parent class method with the same signature.",
    tags: ["oop", "inheritance"],
  },
  {
    id: "c-pointer-1",
    stack: "C",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "What does a pointer store in C?",
    options: [
      "A function definition",
      "A memory address",
      "A floating-point number",
      "A full array value",
    ],
    answerIndex: 1,
    explanation:
      "Pointers store the address of another variable or memory location.",
    tags: ["memory", "pointers"],
  },
  {
    id: "cpp-stl-1",
    stack: "C++",
    difficulty: "Intermediate",
    mode: "debug-duel",
    question: "You need constant-time insertion and removal from both ends. Which STL container fits best?",
    options: ["vector", "deque", "map", "set"],
    answerIndex: 1,
    explanation:
      "A deque is designed for efficient insertions and removals at both ends.",
    tags: ["stl", "data structures"],
  },
  {
    id: "cs-async-1",
    stack: "C#",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "What is the purpose of the async keyword in C#?",
    options: [
      "To create a constructor",
      "To mark a method that can use await",
      "To make code run in parallel automatically",
      "To remove exceptions from a method",
    ],
    answerIndex: 1,
    explanation:
      "The async keyword enables await inside the method and supports asynchronous workflows.",
    tags: ["async", "dotnet"],
  },
  {
    id: "go-interface-1",
    stack: "Go",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "Why are interfaces powerful in Go?",
    options: [
      "They require explicit inheritance chains",
      "They enable implicit behavior-based contracts",
      "They replace all struct usage",
      "They disable composition",
    ],
    answerIndex: 1,
    explanation:
      "Go interfaces are implemented implicitly when a type satisfies the required methods.",
    tags: ["interfaces", "design"],
  },
  {
    id: "rust-ownership-1",
    stack: "Rust",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "What problem does Rust ownership help prevent?",
    options: [
      "Color mismatch in UI design",
      "Memory safety issues like double free and dangling pointers",
      "Slow SQL joins",
      "Lack of package managers",
    ],
    answerIndex: 1,
    explanation:
      "Rust ownership enforces safe memory handling at compile time.",
    tags: ["ownership", "memory"],
  },
  {
    id: "react-state-1",
    stack: "React",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "Why should React state be updated immutably?",
    options: [
      "Because React cannot render arrays",
      "Because mutation can prevent predictable change detection",
      "Because JSX forbids object updates",
      "Because state updates only work in classes",
    ],
    answerIndex: 1,
    explanation:
      "Immutable updates help React detect changes and avoid subtle rendering bugs.",
    tags: ["state", "ui"],
  },
  {
    id: "node-event-loop-1",
    stack: "Node.js",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "What is the event loop in Node.js responsible for?",
    options: [
      "Compiling TypeScript automatically",
      "Managing asynchronous callbacks and task scheduling",
      "Creating database indexes",
      "Encrypting environment variables",
    ],
    answerIndex: 1,
    explanation:
      "The event loop coordinates non-blocking I/O and callback execution in Node.js.",
    tags: ["async", "runtime"],
  },
  {
    id: "sql-join-1",
    stack: "SQL",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "Which JOIN returns matching rows from both tables only?",
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"],
    answerIndex: 2,
    explanation: "INNER JOIN returns rows where the join condition matches in both tables.",
    tags: ["joins", "database"],
  },
  {
    id: "mongo-index-1",
    stack: "MongoDB",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "Why are indexes used in MongoDB?",
    options: [
      "To reduce all storage usage",
      "To speed up query lookups on indexed fields",
      "To automatically back up collections",
      "To replace aggregation pipelines",
    ],
    answerIndex: 1,
    explanation:
      "Indexes improve query performance by reducing the amount of data scanned.",
    tags: ["indexing", "database"],
  },
  {
    id: "html-semantic-1",
    stack: "HTML",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "Why are semantic HTML elements useful?",
    options: [
      "They reduce internet usage",
      "They improve structure, accessibility, and meaning",
      "They make CSS unnecessary",
      "They run JavaScript faster",
    ],
    answerIndex: 1,
    explanation:
      "Semantic elements help browsers, assistive tools, and developers understand page structure.",
    tags: ["accessibility", "markup"],
  },
  {
    id: "css-flex-1",
    stack: "CSS",
    difficulty: "Beginner",
    mode: "output-challenge",
    question: "Which Flexbox property controls alignment along the main axis?",
    options: ["align-items", "justify-content", "align-content", "place-items"],
    answerIndex: 1,
    explanation:
      "justify-content aligns flex items along the main axis.",
    tags: ["layout", "flexbox"],
  },
  {
    id: "git-rebase-1",
    stack: "Git",
    difficulty: "Intermediate",
    mode: "debug-duel",
    question: "What is a common reason to use git rebase instead of git merge?",
    options: [
      "To delete repository history",
      "To create a cleaner linear commit history",
      "To avoid fetching remote changes forever",
      "To permanently disable conflicts",
    ],
    answerIndex: 1,
    explanation:
      "Rebase rewrites commits onto a new base, which often produces a linear history.",
    tags: ["version control", "workflow"],
  },
  {
    id: "devops-ci-1",
    stack: "DevOps",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "What is the main purpose of CI in CI/CD?",
    options: [
      "To manually deploy every build",
      "To frequently integrate and validate code changes",
      "To replace testing completely",
      "To eliminate source control",
    ],
    answerIndex: 1,
    explanation:
      "Continuous Integration helps teams merge changes often and verify them with automated checks.",
    tags: ["ci/cd", "workflow"],
  },
  {
    id: "dsa-stack-1",
    stack: "Data Structures",
    difficulty: "Beginner",
    mode: "concept-sprint",
    question: "Which data structure follows the Last In, First Out principle?",
    options: ["Queue", "Stack", "Heap", "Graph"],
    answerIndex: 1,
    explanation:
      "A stack removes the most recently added element first.",
    tags: ["basics", "stack"],
  },
  {
    id: "algo-binary-1",
    stack: "Algorithms",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "What is the time complexity of binary search on a sorted array?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
    explanation:
      "Binary search cuts the search space in half at each step, giving O(log n).",
    tags: ["search", "complexity"],
  },
  {
    id: "aptitude-ratio-1",
    stack: "Aptitude",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "If the ratio of boys to girls is 3:2 in a class of 30, how many girls are there?",
    options: ["10", "12", "15", "18"],
    answerIndex: 1,
    explanation:
      "There are 5 total parts, so each part is 6. Girls are 2 parts: 2 x 6 = 12.",
    tags: ["ratio", "math"],
  },
  {
    id: "logic-sequence-1",
    stack: "Logical Reasoning",
    difficulty: "Intermediate",
    mode: "concept-sprint",
    question: "Find the next number in the sequence: 2, 6, 12, 20, 30, ?",
    options: ["36", "40", "42", "44"],
    answerIndex: 2,
    explanation:
      "The differences are 4, 6, 8, 10, so the next difference is 12. 30 + 12 = 42.",
    tags: ["sequence", "patterns"],
  },
] as const;
